
struct KeyArgumentMethodChannel {
    // Các thuộc tính cơ bản
    static let idNumber = "idNumber"
    static let birthday = "birthday"
    static let expiredDate = "expiredDate"
    static let languageSdk = "languageSdk"
    static let isShowTutorial = "isShowTutorial"
    static let isDisableTutorial = "isDisableTutorial"
    static let isEnableGotIt = "isEnableGotIt"
    static let readerCardMode = "readerCardMode"
    static let isEnableUploadImage = "isEnableUploadImage"
    static let isEnablePostcodeMatching = "isEnablePostcodeMatching"
    static let inputClientSession = "inputClientSession"
    static let challengeCode = "challengeCode"
    static let readingTagsNFC = "readingTagsNFC"
    static let isEnableCheckChipClone = "isEnableCheckChipClone"
    static let isEnableWaterMark = "isEnableWaterMark"
    static let isEnableAddIdCheckData = "isEnableAddIdCheckData"
    static let isEnableUploadDG = "isEnableUploadDG"
    static let textReadyNFC = "textReadyNFC"
    static let textScanningNFC = "textScanningNFC"
    static let textFinishNFC = "textFinishNFC"
    static let textDetectedNFC = "textDetectedNFC"
    static let nameVideoHelpNFC = "nameVideoHelpNFC"
    static let publicKey = "publicKey"
    static let isEnableEncrypt = "isEnableEncrypt"
    static let modeUploadFile = "modeUploadFile"
    static let flowNFC = "flowNFC"
    static let numberTimesRetryScanNFC = "numberTimesRetryScanNFC"
    static let isEnableCheckSimulator = "isEnableCheckSimulator"
    static let isEnableCheckJailbroken = "isEnableCheckJailbroken"
    static let isAnimatedDismissed = "isAnimatedDismissed"

    // Các thuộc tính bảo mật
    static let accessToken = "accessToken"
    static let tokenId = "tokenId"
    static let tokenKey = "tokenKey"
    static let accessTokenEKYC = "accessTokenEKYC"
    static let tokenIdEKYC = "tokenIdEKYC"
    static let tokenKeyEKYC = "tokenKeyEKYC"

    // Các thuộc tính môi trường
    static let baseUrl = "baseUrl"
    static let urlUploadImage = "urlUploadImage"
    static let urlUploadDataNFC = "urlUploadDataNFC"
    static let urlUploadLogSDK = "urlUploadLogSDK"
    static let urlPostcodeMatching = "urlPostcodeMatching"
    static let headersRequest = "headersRequest"
    static let transactionId = "transactionId"
    static let transactionPartnerId = "transactionPartnerId"
    static let transactionPartnerIDUploadNFC = "transactionPartnerIDUploadNFC"
    static let transactionPartnerIDRecentLocation = "transactionPartnerIDRecentLocation"
    static let transactionPartnerIDOriginalLocation = "transactionPartnerIDOriginalLocation"
    static let nameSSLPinning = "nameSSLPinning"

}


struct KeyResultConstantsNFC {
    static let dataGroupsResult = "DATA_GROUPS_RESULT"
    static let dataNFCResult = "DATA_NFC_RESULT"
    static let clientSessionResult = "CLIENT_SESSION_RESULT"
    static let pathImageAvatar = "IMAGE_AVATAR_CARD_NFC"
    static let hashImageAvatar = "HASH_AVATAR"
    static let dataNFCResultJSON = "LOG_NFC"
    static let postcodeOriginalLocationResult = "POST_CODE_ORIGINAL_LOCATION_RESULT"
    static let postcodeRecentLocationResult = "POST_CODE_RECENT_LOCATION_RESULT"
    static let hashAvatarForLog = "HASH_AVATAR_FOR_LOG"
    static let hashDGsForLog = "HASH_DGS_FOR_LOG"
    static let nfcForLog = "NFC_FOR_LOG"
    static let matchingOriginForLog = "MATCHING_ORIGIN_FOR_LOG"
    static let matchingResidenceForLog = "MATCHING_RESIDENCE_FOR_LOG"
}