
struct KeyArgumentMethodChannel {
    // Các thuộc tính cơ bản
    static let idNumber = "id_number"
    static let birthday = "birthday"
    static let expiredDate = "expired_date"
    static let languageSdk = "language_sdk"
    static let isShowTutorial = "is_show_tutorial"
    static let isDisableTutorial = "is_disable_tutorial"
    static let isEnableGotIt = "is_enable_got_it"
    static let isShowLogo = "is_show_logo"
    static let readerCardMode = "reader_card_mode"
    static let isEnableUploadImage = "is_enable_upload_image"
    static let isEnablePostcodeMatching = "is_enable_postcode_matching"
    static let inputClientSession = "input_client_session"
    static let challengeCode = "challenge_code"
    static let readingTagsNFC = "reading_tags_nfc"
    static let isEnableCheckChipClone = "is_enable_check_chip_clone"
    static let isEnableWaterMark = "is_enable_water_mark"
    static let isEnableAddIdCheckData = "is_enable_add_id_check_data"
    static let isEnableUploadDG = "is_enable_upload_dg"
    static let textReadyNFC = "text_ready_nfc"
    static let textScanningNFC = "text_scanning_nfc"
    static let textFinishNFC = "text_finish_nfc"
    static let textDetectedNFC = "text_detected_nfc"
    static let nameVideoHelpNFC = "name_video_help_nfc"
    static let publicKey = "public_key"
    static let isEnableEncrypt = "is_enable_encrypt"
    static let modeUploadFile = "mode_upload_file"
    static let flowNFC = "flow_nfc"
    static let numberTimesRetryScanNFC = "number_times_retry_scan_nfc"
    static let isEnableCheckSimulator = "is_enable_check_simulator"
    static let isEnableCheckJailbroken = "is_enable_check_jailbroken"
    static let isAnimatedDismissed = "is_animated_dismissed"

    // Các thuộc tính bảo mật
    static let accessToken = "access_token"
    static let tokenId = "token_id"
    static let tokenKey = "token_key"
    static let accessTokenEKYC = "access_token_ekyc"
    static let tokenIdEKYC = "token_id_ekyc"
    static let tokenKeyEKYC = "token_key_ekyc"

    // Các thuộc tính môi trường
    static let baseUrl = "base_url"
    static let urlUploadImage = "url_upload_image"
    static let urlUploadDataNFC = "url_upload_data_nfc"
    static let urlUploadLogSDK = "url_upload_log_sdk"
    static let urlPostcodeMatching = "url_postcode_matching"
    static let headersRequest = "headers_request"
    static let transactionId = "transaction_id"
    static let transactionPartnerId = "transaction_partner_id"
    static let transactionPartnerIDUploadNFC = "transaction_partner_id_upload_nfc"
    static let transactionPartnerIDRecentLocation = "transaction_partner_id_recent_location"
    static let transactionPartnerIDOriginalLocation = "transaction_partner_id_original_location"
    static let nameSSLPinning = "name_ssl_pinning"
    static let modeButtonHeaderBar = "mode_button_header_bar"

}


struct KeyResultConstantsNFC {
    static let dataGroupsResult = "DATA_GROUPS_RESULT"
    static let dataNFCResult = "DATA_NFC_RESULT"
    static let clientSessionResult = "CLIENT_SESSION_RESULT"
    static let pathImageAvatar = "PATH_IMAGE_AVATAR"
    static let hashImageAvatar = "HASH_IMAGE_AVATAR"
    static let dataNFCResultJSON = "LOG_NFC"
    static let postcodeOriginalLocationResult = "POST_CODE_ORIGINAL_LOCATION_RESULT"
    static let postcodeRecentLocationResult = "POST_CODE_RECENT_LOCATION_RESULT"
    static let hashAvatarForLog = "HASH_AVATAR_FOR_LOG"
    static let hashDGsForLog = "HASH_DGS_FOR_LOG"
    static let nfcForLog = "NFC_FOR_LOG"
    static let matchingOriginForLog = "MATCHING_ORIGIN_FOR_LOG"
    static let matchingResidenceForLog = "MATCHING_RESIDENCE_FOR_LOG"
}
