import 'enum_nfc.dart';
import 'nfc_config.dart';

/// Predefined configurations for common NFC use cases
class NfcPresets {
  /// QR -> NFC flow (no manual inputs needed)
  static ICNfcConfig qrToNfc({
    ICNfcLanguage languageSdk = ICNfcLanguage.icnfc_vi,
    bool isShowTutorial = false,
    bool isEnableGotIt = false,
    bool isEnableUploadImage = true,
    bool isEnablePostcodeMatching = false,
    String inputClientSession = '',
    List<String> readingTagsNFC = const [],
    String nameVideoHelpNFC = '',
    String accessToken = '',
    String tokenId = '',
    String tokenKey = '',
    String accessTokenEKYC = '',
    String tokenIdEKYC = '',
    String tokenKeyEKYC = '',
    String baseUrl = '',
    ModeButtonHeaderBar modeButtonHeaderBar = ModeButtonHeaderBar.leftButton,
    bool isShowLogo = false,
  }) => ICNfcConfig(
    accessToken: accessToken,
    tokenId: tokenId,
    tokenKey: tokenKey,
    accessTokenEKYC: accessTokenEKYC,
    tokenIdEKYC: tokenIdEKYC,
    tokenKeyEKYC: tokenKeyEKYC,
    baseUrl: baseUrl,
    languageSdk: languageSdk,
    isShowTutorial: isShowTutorial,
    isEnableGotIt: isEnableGotIt,
    readerCardMode: ReaderCardMode.qrCode,
    isEnableUploadImage: isEnableUploadImage,
    isEnablePostcodeMatching: isEnablePostcodeMatching,
    inputClientSession: inputClientSession,
    readingTagsNFC: readingTagsNFC,
    nameVideoHelpNFC: nameVideoHelpNFC,
    modeButtonHeaderBar: modeButtonHeaderBar,
    isShowLogo: isShowLogo,
  );

  /// MRZ -> NFC flow (no manual inputs needed)
  static ICNfcConfig mrzToNfc({
    String accessToken = '',
    String tokenId = '',
    String tokenKey = '',
    String accessTokenEKYC = '',
    String tokenIdEKYC = '',
    String tokenKeyEKYC = '',
    String baseUrl = '',
    ICNfcLanguage languageSdk = ICNfcLanguage.icnfc_vi,
    bool isShowTutorial = false,
    bool isEnableGotIt = false,
    bool isEnableUploadImage = true,
    bool isEnablePostcodeMatching = false,
    String inputClientSession = '',
    List<String> readingTagsNFC = const [],
    String nameVideoHelpNFC = '',
    ModeButtonHeaderBar modeButtonHeaderBar = ModeButtonHeaderBar.leftButton,
    bool isShowLogo = false,
  }) => ICNfcConfig(
    accessToken: accessToken,
    tokenId: tokenId,
    tokenKey: tokenKey,
    accessTokenEKYC: accessTokenEKYC,
    tokenIdEKYC: tokenIdEKYC,
    tokenKeyEKYC: tokenKeyEKYC,
    baseUrl: baseUrl,
    languageSdk: languageSdk,
    isShowTutorial: isShowTutorial,
    isEnableGotIt: isEnableGotIt,
    readerCardMode: ReaderCardMode.mrzCode,
    isEnableUploadImage: isEnableUploadImage,
    isEnablePostcodeMatching: isEnablePostcodeMatching,
    inputClientSession: inputClientSession,
    readingTagsNFC: readingTagsNFC,
    nameVideoHelpNFC: nameVideoHelpNFC,
    modeButtonHeaderBar: modeButtonHeaderBar,
    isShowLogo: isShowLogo,
  );

  /// Manual NFC with SDK UI
  static ICNfcConfig manualWithUi({
    String accessToken = '',
    String tokenId = '',
    String tokenKey = '',
    String accessTokenEKYC = '',
    String tokenIdEKYC = '',
    String tokenKeyEKYC = '',
    String baseUrl = '',
    required String idNumber,
    required String birthday,
    required String expiredDate,
    ICNfcLanguage languageSdk = ICNfcLanguage.icnfc_vi,
    bool isShowTutorial = false,
    bool isEnableGotIt = false,
    bool isEnableUploadImage = true,
    bool isEnablePostcodeMatching = false,
    String inputClientSession = '',
    List<String> readingTagsNFC = const [],
    String nameVideoHelpNFC = '',
    ModeButtonHeaderBar modeButtonHeaderBar = ModeButtonHeaderBar.leftButton,
    bool isShowLogo = false,
  }) => ICNfcConfig(
    accessToken: accessToken,
    tokenId: tokenId,
    tokenKey: tokenKey,
    accessTokenEKYC: accessTokenEKYC,
    tokenIdEKYC: tokenIdEKYC,
    tokenKeyEKYC: tokenKeyEKYC,
    baseUrl: baseUrl,
    idNumber: idNumber,
    birthday: birthday,
    expiredDate: expiredDate,
    languageSdk: languageSdk,
    isShowTutorial: isShowTutorial,
    isEnableGotIt: isEnableGotIt,
    readerCardMode: ReaderCardMode.nfcReader,
    isEnableUploadImage: isEnableUploadImage,
    isEnablePostcodeMatching: isEnablePostcodeMatching,
    inputClientSession: inputClientSession,
    readingTagsNFC: readingTagsNFC,
    nameVideoHelpNFC: nameVideoHelpNFC,
    modeButtonHeaderBar: modeButtonHeaderBar,
    isShowLogo: isShowLogo,
  );

  /// Manual NFC without SDK UI
  static ICNfcConfig manualWithoutUi({
    required String idNumber,
    required String birthday,
    required String expiredDate,
    String accessToken = '',
    String tokenId = '',
    String tokenKey = '',
    String accessTokenEKYC = '',
    String tokenIdEKYC = '',
    String tokenKeyEKYC = '',
    String baseUrl = '',
    ICNfcLanguage languageSdk = ICNfcLanguage.icnfc_vi,
    bool isEnableUploadImage = false,
    bool isEnablePostcodeMatching = false,
    String inputClientSession = '',
    List<String> readingTagsNFC = const [],
    String nameVideoHelpNFC = '',
    ModeButtonHeaderBar modeButtonHeaderBar = ModeButtonHeaderBar.leftButton,
    bool isShowLogo = false,
  }) => ICNfcConfig(
    accessToken: accessToken,
    tokenId: tokenId,
    tokenKey: tokenKey,
    accessTokenEKYC: accessTokenEKYC,
    tokenIdEKYC: tokenIdEKYC,
    tokenKeyEKYC: tokenKeyEKYC,
    baseUrl: baseUrl,
    idNumber: idNumber,
    birthday: birthday,
    expiredDate: expiredDate,
    readerCardMode: ReaderCardMode.nfcOutside,
    isEnableUploadImage: isEnableUploadImage,
    isEnablePostcodeMatching: isEnablePostcodeMatching,
    inputClientSession: inputClientSession,
    readingTagsNFC: readingTagsNFC,
    nameVideoHelpNFC: nameVideoHelpNFC,
    modeButtonHeaderBar: modeButtonHeaderBar,
    isShowLogo: isShowLogo,
  );
}
