group = "com.vnpt.flutter_plugin_ic_nfc"
version = "1.0-SNAPSHOT"

buildscript {
    ext.kotlin_version = "2.1.0"
    repositories {
        google()
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.9.1")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: "com.android.library"
apply plugin: "kotlin-android"

repositories {
    maven { url "${projectDir}/local-maven" }
}

android {
    namespace = "com.vnpt.flutter_plugin_ic_nfc"

    compileSdk = 35
    ndkVersion = "27.0.12077973"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
        test.java.srcDirs += "src/test/kotlin"
    }

    defaultConfig {
        minSdk = 21
    }

    androidResources {
        noCompress += "bic"
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
    }

    packaging {
        resources.excludes += '/META-INF/versions/9/OSGI-INF/MANIFEST.MF'
    }

    dependencies {
        implementation 'com.vnpt:vnpt-nfc-sdk:1.8.6'
        implementation 'com.vnpt:scanqr-ic-sdk:1.0.6'
        implementation 'androidx.core:core-ktx:1.8.0'
        implementation 'androidx.appcompat:appcompat:1.6.1'
        implementation 'com.google.android.material:material:1.5.0'
        implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
        // NFC
        implementation 'org.jmrtd:jmrtd:0.8.5'
        implementation 'net.sf.scuba:scuba-sc-android:0.0.26'
        implementation('org.ejbca.cvc:cert-cvc:1.4.13') {
            exclude group: 'org.bouncycastle', module: 'bcprov-jdk15on'
            exclude group: 'org.bouncycastle', module: 'bcpkix-jdk15on'
        }
        implementation 'org.bouncycastle:bcpkix-jdk18on:1.78'
        implementation 'org.bouncycastle:bcprov-jdk18on:1.78'
        implementation 'commons-io:commons-io:2.6'
        implementation 'com.airbnb.android:lottie:6.0.1'
        implementation "me.dm7.barcodescanner:zxing:1.9.8"
        implementation "androidx.camera:camera-core:1.4.2"
        implementation "androidx.camera:camera-camera2:1.4.2"
        implementation "androidx.camera:camera-lifecycle:1.4.2"
        implementation "androidx.camera:camera-view:1.4.2"
        implementation "com.squareup.okhttp3:okhttp:4.11.0"
        implementation 'com.google.code.gson:gson:2.10.1'

        testImplementation("org.jetbrains.kotlin:kotlin-test")
        testImplementation("org.mockito:mockito-core:5.0.0")
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()

            testLogging {
               events "passed", "skipped", "failed", "standardOut", "standardError"
               outputs.upToDateWhen {false}
               showStandardStreams = true
            }
        }
    }
}
