package com.vnpt.flutter_plugin_ic_nfc

object KeyArgumentMethodChannel {
    // Các thuộc tính cơ bản
    const val ID_NUMBER: String = "id_number"
    const val BIRTHDAY: String = "birthday"
    const val EXPIRED_DATE: String = "expired_date"
    const val LANGUAGE_SDK: String = "language_sdk"
    const val IS_SHOW_TUTORIAL: String = "is_show_tutorial"
    const val IS_SHOW_LOGO: String = "is_show_logo"

    const val MODE_BUTTON_HEADER_BAR: String = "mode_button_header_bar"

    const val IS_DISABLE_TUTORIAL: String = "is_disable_tutorial"
    const val IS_ENABLE_GOT_IT: String = "is_enable_got_it"
    const val READER_CARD_MODE: String = "reader_card_mode"
    const val IS_ENABLE_UPLOAD_IMAGE: String = "is_enable_upload_image"
    const val IS_ENABLE_POSTCODE_MATCHING: String = "is_enable_postcode_matching"
    const val INPUT_CLIENT_SESSION: String = "input_client_session"
    const val CHALLENGE_CODE: String = "challenge_code"
    const val READING_TAGS_NFC: String = "reading_tags_nfc"
    const val IS_ENABLE_CHECK_CHIP_CLONE: String = "is_enable_check_chip_clone"
    const val IS_ENABLE_WATER_MARK: String = "is_enable_water_mark"
    const val IS_ENABLE_ADD_ID_CHECK_DATA: String = "is_enable_add_id_check_data"
    const val IS_ENABLE_UPLOAD_DG: String = "is_enable_upload_dg"
    const val TEXT_READY_NFC: String = "text_ready_nfc"
    const val TEXT_SCANNING_NFC: String = "text_scanning_nfc"
    const val TEXT_FINISH_NFC: String = "text_finish_nfc"
    const val TEXT_DETECTED_NFC: String = "text_detected_nfc"
    const val NAME_VIDEO_HELP_NFC: String = "name_video_help_nfc"
    const val PUBLIC_KEY: String = "public_key"
    const val IS_ENABLE_ENCRYPT: String = "is_enable_encrypt"
    const val MODE_UPLOAD_FILE: String = "mode_upload_file"
    const val FLOW_NFC: String = "flow_nfc"
    const val NUMBER_TIMES_RETRY_SCAN_NFC: String = "number_times_retry_scan_nfc"
    const val IS_ENABLE_CHECK_SIMULATOR: String = "is_enable_check_simulator"
    const val IS_ENABLE_CHECK_JAILBROKEN: String = "is_enable_check_jailbroken"
    const val IS_ANIMATED_DISMISSED: String = "is_animated_dismissed"

    // Các thuộc tính bảo mật
    const val ACCESS_TOKEN: String = "access_token"
    const val TOKEN_ID: String = "token_id"
    const val TOKEN_KEY: String = "token_key"
    const val ACCESS_TOKEN_EKYC: String = "access_token_ekyc"
    const val TOKEN_ID_EKYC: String = "token_id_ekyc"
    const val TOKEN_KEY_EKYC: String = "token_key_ekyc"

    // Các thuộc tính môi trường
    const val BASE_URL: String = "base_url"
    const val URL_UPLOAD_IMAGE: String = "url_upload_image"
    const val URL_UPLOAD_DATA_NFC: String = "url_upload_data_nfc"
    const val URL_UPLOAD_LOG_SDK: String = "url_upload_log_sdk"
    const val URL_POSTCODE_MATCHING: String = "url_postcode_matching"
    const val HEADERS_REQUEST: String = "headers_request"
    const val TRANSACTION_ID: String = "transaction_id"
    const val TRANSACTION_PARTNER_ID: String = "transaction_partner_id"
    const val TRANSACTION_PARTNER_ID_UPLOAD_NFC: String = "transaction_partner_id_upload_nfc"
    const val TRANSACTION_PARTNER_ID_RECENT_LOCATION: String = "transaction_partner_id_recent_location"
    const val TRANSACTION_PARTNER_ID_ORIGINAL_LOCATION: String = "transaction_partner_id_original_location"
    const val NAME_SSL_PINNING: String = "name_ssl_pinning"
}