package com.vnpt.flutter_plugin_ic_nfc

object KeyArgumentMethodChannel {
    // Các thuộc tính cơ bản
    const val ID_NUMBER: String = "idNumber"
    const val BIRTHDAY: String = "birthday"
    const val EXPIRED_DATE: String = "expiredDate"
    const val LANGUAGE_SDK: String = "languageSdk"
    const val IS_SHOW_TUTORIAL: String = "isShowTutorial"
    const val IS_DISABLE_TUTORIAL: String = "isDisableTutorial"
    const val IS_ENABLE_GOT_IT: String = "isEnableGotIt"
    const val READER_CARD_MODE: String = "readerCardMode"
    const val IS_ENABLE_UPLOAD_IMAGE: String = "isEnableUploadImage"
    const val IS_ENABLE_POSTCODE_MATCHING: String = "isEnablePostcodeMatching"
    const val INPUT_CLIENT_SESSION: String = "inputClientSession"
    const val CHALLENGE_CODE: String = "challengeCode"
    const val READING_TAGS_NFC: String = "readingTagsNFC"
    const val IS_ENABLE_CHECK_CHIP_CLONE: String = "isEnableCheckChipClone"
    const val IS_ENABLE_WATER_MARK: String = "isEnableWaterMark"
    const val IS_ENABLE_ADD_ID_CHECK_DATA: String = "isEnableAddIdCheckData"
    const val IS_ENABLE_UPLOAD_DG: String = "isEnableUploadDG"
    const val TEXT_READY_NFC: String = "textReadyNFC"
    const val TEXT_SCANNING_NFC: String = "textScanningNFC"
    const val TEXT_FINISH_NFC: String = "textFinishNFC"
    const val TEXT_DETECTED_NFC: String = "textDetectedNFC"
    const val NAME_VIDEO_HELP_NFC: String = "nameVideoHelpNFC"
    const val PUBLIC_KEY: String = "publicKey"
    const val IS_ENABLE_ENCRYPT: String = "isEnableEncrypt"
    const val MODE_UPLOAD_FILE: String = "modeUploadFile"
    const val FLOW_NFC: String = "flowNFC"
    const val NUMBER_TIMES_RETRY_SCAN_NFC: String = "numberTimesRetryScanNFC"
    const val IS_ENABLE_CHECK_SIMULATOR: String = "isEnableCheckSimulator"
    const val IS_ENABLE_CHECK_JAILBROKEN: String = "isEnableCheckJailbroken"
    const val IS_ANIMATED_DISMISSED: String = "isAnimatedDismissed"

    // Các thuộc tính bảo mật
    const val ACCESS_TOKEN: String = "accessToken"
    const val TOKEN_ID: String = "tokenId"
    const val TOKEN_KEY: String = "tokenKey"
    const val ACCESS_TOKEN_EKYC: String = "accessTokenEKYC"
    const val TOKEN_ID_EKYC: String = "tokenIdEKYC"
    const val TOKEN_KEY_EKYC: String = "tokenKeyEKYC"

    // Các thuộc tính môi trường
    const val BASE_URL: String = "baseUrl"
    const val URL_UPLOAD_IMAGE: String = "urlUploadImage"
    const val URL_UPLOAD_DATA_NFC: String = "urlUploadDataNFC"
    const val URL_UPLOAD_LOG_SDK: String = "urlUploadLogSDK"
    const val URL_POSTCODE_MATCHING: String = "urlPostcodeMatching"
    const val HEADERS_REQUEST: String = "headersRequest"
    const val TRANSACTION_ID: String = "transactionId"
    const val TRANSACTION_PARTNER_ID: String = "transactionPartnerId"
    const val TRANSACTION_PARTNER_ID_UPLOAD_NFC: String = "transactionPartnerIDUploadNFC"
    const val TRANSACTION_PARTNER_ID_RECENT_LOCATION: String = "transactionPartnerIDRecentLocation"
    const val TRANSACTION_PARTNER_ID_ORIGINAL_LOCATION: String = "transactionPartnerIDOriginalLocation"
    const val NAME_SSL_PINNING: String = "nameSSLPinning"
}